      # используем язык java. Travis CI поддерживает другие языки тоже.
      language: java
      jdk:
        - openjdk14


      # используем режим обычного пользователя для сборки проекта.
      sudo: false

      # после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
      # Здесь используется сторонни сервис https://codecov.io/
      after_success:
        - bash <(curl -s https://codecov.io/bash)

      # Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
      notifications:
        email:
          recipients:
            - sport_piter@mail.ru
          on_success: never # default: change
          on_failure: always # default: always

      env:
        global:
          - CODECOV_TOKEN = "c785c4ba-3ae2-4a1e-a313-c8dfbc136352"

